version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
        update-types: ['version-update:semver-major']
      - dependency-name: org.springdoc:springdoc-openapi-starter-webmvc-ui
        update-types: ['version-update:semver-major']
      - dependency-name: com.azure.spring:spring-cloud-azure-dependencies
        versions: ['7.4.0']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
